spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/directory
    username: user
    password: user

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
